/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AISignal {
  'coinSymbol' : string,
  'reasoning' : string,
  'timestamp' : bigint,
  'recommendation' : Recommendation,
  'confidence' : bigint,
}
export interface Coin {
  'change24h' : number,
  'marketCap' : number,
  'name' : string,
  'volume24h' : number,
  'updatedAt' : bigint,
  'price' : number,
  'symbol' : string,
}
export type Recommendation = { 'buy' : null } |
  { 'hold' : null } |
  { 'sell' : null };
export interface UserProfile {
  'country' : string,
  'username' : string,
  'phone' : string,
  'demoBalance' : bigint,
  'hasCompletedOnboarding' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToWatchlist' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAISignalForCoin' : ActorMethod<[string], [] | [AISignal]>,
  'getAISignals' : ActorMethod<[], Array<AISignal>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoinDetail' : ActorMethod<[string], [] | [Coin]>,
  'getCoinList' : ActorMethod<[], Array<Coin>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWatchlist' : ActorMethod<[], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromWatchlist' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];