/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Recommendation = IDL.Variant({
  'buy' : IDL.Null,
  'hold' : IDL.Null,
  'sell' : IDL.Null,
});
export const AISignal = IDL.Record({
  'coinSymbol' : IDL.Text,
  'reasoning' : IDL.Text,
  'timestamp' : IDL.Int,
  'recommendation' : Recommendation,
  'confidence' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'country' : IDL.Text,
  'username' : IDL.Text,
  'phone' : IDL.Text,
  'demoBalance' : IDL.Nat,
  'hasCompletedOnboarding' : IDL.Bool,
});
export const Coin = IDL.Record({
  'change24h' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'name' : IDL.Text,
  'volume24h' : IDL.Float64,
  'updatedAt' : IDL.Int,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToWatchlist' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAISignalForCoin' : IDL.Func([IDL.Text], [IDL.Opt(AISignal)], ['query']),
  'getAISignals' : IDL.Func([], [IDL.Vec(AISignal)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoinDetail' : IDL.Func([IDL.Text], [IDL.Opt(Coin)], ['query']),
  'getCoinList' : IDL.Func([], [IDL.Vec(Coin)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Recommendation = IDL.Variant({
    'buy' : IDL.Null,
    'hold' : IDL.Null,
    'sell' : IDL.Null,
  });
  const AISignal = IDL.Record({
    'coinSymbol' : IDL.Text,
    'reasoning' : IDL.Text,
    'timestamp' : IDL.Int,
    'recommendation' : Recommendation,
    'confidence' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'country' : IDL.Text,
    'username' : IDL.Text,
    'phone' : IDL.Text,
    'demoBalance' : IDL.Nat,
    'hasCompletedOnboarding' : IDL.Bool,
  });
  const Coin = IDL.Record({
    'change24h' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'name' : IDL.Text,
    'volume24h' : IDL.Float64,
    'updatedAt' : IDL.Int,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToWatchlist' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAISignalForCoin' : IDL.Func([IDL.Text], [IDL.Opt(AISignal)], ['query']),
    'getAISignals' : IDL.Func([], [IDL.Vec(AISignal)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoinDetail' : IDL.Func([IDL.Text], [IDL.Opt(Coin)], ['query']),
    'getCoinList' : IDL.Func([], [IDL.Vec(Coin)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };